import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { extname } from "node:path";
import { INDEXABLE_EXTENSIONS, MAX_FILE_SIZE_BYTES } from "../../config";

export function computeBufferHash(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}

// Files whose leading YAML frontmatter is metadata, not content. A status:/tags:
// edit bumps mtime and changes the bytes, but the embedding ignores frontmatter —
// so hashing it would force a needless GPU re-embed on every metadata touch.
const FRONTMATTER_EXTENSIONS = new Set([".md", ".mdx"]);

// Leading YAML frontmatter: a whole `---` line at the very top (NOT a bare
// `startsWith("---")`, which would also match a `---` thematic break or `--- x`),
// through the next whole `---`/`...` line. Anchored at string start (no `m` flag)
// with an optional BOM, so only true file-leading frontmatter matches; a doc that
// opens with a thematic break and no closing fence is left untouched.
const FRONTMATTER_BLOCK =
  /^\uFEFF?---[ \t]*\r?\n[\s\S]*?\r?\n(?:---|\.\.\.)[ \t]*(?:\r?\n|$)/;

/** Strip leading YAML frontmatter from markdown bytes; returns input unchanged otherwise. */
export function stripMarkdownFrontmatter(buffer: Buffer): Buffer {
  const text = buffer.toString("utf8");
  const match = text.match(FRONTMATTER_BLOCK);
  if (!match) return buffer;
  return Buffer.from(text.slice(match[0].length), "utf8");
}

/**
 * Hash file content for change detection. For markdown, YAML frontmatter is
 * stripped first so a metadata-only edit doesn't bust `isFileCached` and trigger
 * a re-embed; every other file hashes its exact bytes. Must be used identically
 * across the catchup, watcher, and worker hash paths or they will disagree and
 * re-index in a loop.
 */
export function computeContentHash(buffer: Buffer, filePath: string): string {
  if (FRONTMATTER_EXTENSIONS.has(extname(filePath).toLowerCase())) {
    return computeBufferHash(stripMarkdownFrontmatter(buffer));
  }
  return computeBufferHash(buffer);
}

export function hasNullByte(buffer: Buffer, sampleLength = 1024): boolean {
  const length = Math.min(buffer.length, sampleLength);
  for (let i = 0; i < length; i++) {
    if (buffer[i] === 0) return true;
  }
  return false;
}

export async function readFileSnapshot(
  filePath: string,
): Promise<{ buffer: Buffer; mtimeMs: number; size: number }> {
  const handle = await fs.promises.open(filePath, "r");
  try {
    const before = await handle.stat();
    if (before.size > MAX_FILE_SIZE_BYTES) {
      throw new Error("File exceeds maximum allowed size");
    }
    const size = before.size;
    const buffer = size > 0 ? Buffer.allocUnsafe(size) : Buffer.alloc(0);
    if (size > 0) {
      await handle.read(buffer, 0, size, 0);
    }
    const after = await handle.stat();
    if (before.mtimeMs !== after.mtimeMs || before.size !== after.size) {
      throw new Error("File changed during read");
    }
    return { buffer, mtimeMs: after.mtimeMs, size: after.size };
  } finally {
    await handle.close();
  }
}

// Check if a file should be indexed (extension and size).
export function isIndexableFile(filePath: string, size?: number): boolean {
  const ext = extname(filePath).toLowerCase();
  const basename = path.basename(filePath).toLowerCase();
  if (!INDEXABLE_EXTENSIONS.has(ext) && !INDEXABLE_EXTENSIONS.has(basename)) {
    return false;
  }

  const withinSize = (s: number) => s > 0 && s <= MAX_FILE_SIZE_BYTES;

  if (typeof size === "number") {
    return withinSize(size);
  }

  try {
    const stats = fs.statSync(filePath);
    return withinSize(stats.size);
  } catch {
    return false;
  }
}

export function isIndexablePath(filePath: string): boolean {
  return isIndexableFile(filePath);
}

// Well-known machine-generated markers emitted at the top of codegen output.
// Tools (protoc, graphql-codegen, Apollo, Relay, Go `stringer`, OpenAPI, etc.)
// stamp one of these in a banner comment. Matched against only the first few KB
// because the banner is always at the very top — this keeps a hand-written
// "do not edit this section" note deep in a real file from being misclassified.
const GENERATED_MARKER =
  /@generated\b|\bDO NOT EDIT\b|Code generated by |auto-?generated by |This (?:file|code) (?:is|was) (?:\w+[ -])?generated|machine generated|@autogenerated\b/i;
const GENERATED_SNIFF_BYTES = 2048;

/**
 * Detect machine-generated source by its banner. Generated files flood both the
 * vector index and the symbol graph (codegen types rank as god nodes), so they
 * are skipped at index time. Path globs in `ignore-patterns.ts` catch the
 * obvious filenames; this catches the rest by content.
 */
export function isGeneratedContent(buffer: Buffer): boolean {
  const head = buffer.subarray(0, GENERATED_SNIFF_BYTES).toString("utf-8");
  return GENERATED_MARKER.test(head);
}

export function formatDenseSnippet(text: string, maxLength = 1500): string {
  const clean = text ?? "";
  if (clean.length <= maxLength) return clean;
  return `${clean.slice(0, maxLength)}...`;
}

export function isDevelopment(): boolean {
  // Return false when running from within node_modules
  if (__dirname.includes("node_modules")) {
    return false;
  }
  // Return true only when NODE_ENV is explicitly "development"
  if (process.env.NODE_ENV === "development") {
    return true;
  }
  // Otherwise return false (production/other environments)
  return false;
}
