ignoredBuiltDependencies:
  - msgpackr-extract
  - onnxruntime-node
  - protobufjs
  - sharp
  - usearch

onlyBuiltDependencies:
  - '"'
  - ','
  - '-'
  - '['
  - ']'
  - b
  - d
  - e
  - esbuild
  - i
  - l
  - lmdb
  - m
  - n
  - o
  - r
  - s
  - simsimd
  - t
  - u
  - x
