import ignore from "ignore";
import { describe, expect, it } from "vitest";
import { DEFAULT_IGNORE_PATTERNS } from "../src/lib/index/ignore-patterns";
import { isGeneratedContent } from "../src/lib/utils/file-utils";

/**
 * Phase 5 — generated-code exclusion. Two complementary gates: filename/dir
 * globs (walker, via DEFAULT_IGNORE_PATTERNS) and a content header sniff
 * (orchestrator, via isGeneratedContent). Codegen output otherwise floods the
 * vector index and ranks generated types as god nodes in the symbol graph.
 */

const buf = (s: string) => Buffer.from(s, "utf-8");

describe("isGeneratedContent", () => {
  it("flags the common codegen banners", () => {
    expect(
      isGeneratedContent(buf("/* @generated */\nexport const x = 1;")),
    ).toBe(true);
    // Go convention
    expect(
      isGeneratedContent(
        buf("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb"),
      ),
    ).toBe(true);
    // Bare DO NOT EDIT
    expect(
      isGeneratedContent(
        buf("# DO NOT EDIT — regenerate with make gen\nclass Foo: pass"),
      ),
    ).toBe(true);
    // graphql-codegen / Apollo phrasing
    expect(
      isGeneratedContent(
        buf(
          "// This file was automatically generated and should not be edited.\n",
        ),
      ),
    ).toBe(true);
    expect(
      isGeneratedContent(buf("// @generated by Apollo\nstruct Q {}")),
    ).toBe(true);
  });

  it("does not flag ordinary hand-written source", () => {
    expect(
      isGeneratedContent(
        buf("export function add(a: number, b: number) {\n  return a + b;\n}"),
      ),
    ).toBe(false);
    expect(
      isGeneratedContent(
        buf("// Copyright 2026. Licensed under Apache-2.0.\nclass Service {}"),
      ),
    ).toBe(false);
    // "generated" used as a normal word, not a banner
    expect(
      isGeneratedContent(
        buf("// builds the generated report from rows\nfunction report() {}"),
      ),
    ).toBe(false);
  });

  it("only sniffs the header — a DO NOT EDIT note deep in a real file is ignored", () => {
    const body = `${"const x = 1;\n".repeat(400)}// DO NOT EDIT this constant\n`;
    expect(body.length).toBeGreaterThan(2048);
    expect(isGeneratedContent(buf(body))).toBe(false);
  });

  // The banner a generator *emits* used to classify the generator itself as
  // generated output, silently erasing hand-written source from the index.
  it("does not flag a generator by the banner it emits", () => {
    const generator = `/**
 * Pure render logic for FreeRADIUS clients.conf, shared by scripts/generate.ts.
 */
export function render(list: string[]) {
  const lines: string[] = [
    '# Auto-generated by generate-radius-clients-conf.ts — DO NOT EDIT.',
  ];
  return lines.concat(list).join("\\n");
}`;
    expect(isGeneratedContent(buf(generator), "render.ts")).toBe(false);
  });

  it("does not flag a comment that quotes another file's do-not-edit rule", () => {
    const config = `// Beyond platform — dotmd configuration

export const root = [
  'docs/plans',
  // Its own README says "do not edit the body", and prepending frontmatter
  // would violate that, so it is excluded here instead.
  'docs',
];`;
    expect(isGeneratedContent(buf(config), "dotmd.config.mjs")).toBe(false);
  });

  it("keeps the shebang+usage header of a hand-written script indexable", () => {
    const script = `#!/usr/bin/env node
// \`just dev-branch [create|delete|status|refresh]\`
// Manages a per-developer Neon branch and writes connection strings.

function main() {
  return ['# Auto-generated by \`just dev-branch\`. Do not edit.'];
}`;
    expect(isGeneratedContent(buf(script), "dev-branch.mjs")).toBe(false);
  });

  describe("doc-like files", () => {
    it("flags a generated-body fence after frontmatter", () => {
      const doc = `---
title: Permission catalog
updated: 2026-08-17
---
<!-- generated-body:start -->

# Permission catalog
`;
      expect(isGeneratedContent(buf(doc), "permissions-reference.md")).toBe(
        true,
      );
    });

    it("flags markdown-magic style content fences", () => {
      const doc = `<!-- AUTO-GENERATED-CONTENT:START -->\n# Table\n`;
      expect(isGeneratedContent(buf(doc), "README.md")).toBe(true);
    });

    // "do not edit" on prose is a human instruction, not a codegen banner.
    it("does not flag an archived snapshot told not to be edited", () => {
      const doc = `<!-- Archived from https://exa-pedia.com/docs/cruiser/faq/ on 2026-07-30.
     Vendor documentation snapshot, retained as evidence.
     Verbatim capture; do not edit the body. -->

# FAQ

Frequently asked questions.
`;
      expect(isGeneratedContent(buf(doc), "faq.md")).toBe(false);
    });

    it("does not read markdown headings as comment banners", () => {
      const doc = `# Release process

Do not edit the generated changelog by hand.
`;
      expect(isGeneratedContent(buf(doc), "release.md")).toBe(false);
    });
  });
});

describe("DEFAULT_IGNORE_PATTERNS — generated filenames", () => {
  const ig = ignore().add(DEFAULT_IGNORE_PATTERNS);
  const ignored = (p: string) => ig.ignores(p);

  it("excludes well-known codegen filename conventions", () => {
    expect(ignored("api/service.pb.go")).toBe(true);
    expect(ignored("proto/messages_pb2.py")).toBe(true);
    expect(ignored("proto/messages_pb2_grpc.py")).toBe(true);
    expect(ignored("packages/web/src/gql/graphql.generated.ts")).toBe(true);
    expect(ignored("ios/App/Operations.graphql.swift")).toBe(true);
    expect(ignored("lib/model.freezed.dart")).toBe(true);
    expect(ignored("src/__generated__/types.ts")).toBe(true);
    expect(
      ignored(
        "packages/ios/BeyondApp/GraphQL/Generated/BeyondGraphQL.graphql.swift",
      ),
    ).toBe(true);
    // graphql-codegen client-preset (no @generated banner)
    expect(ignored("packages/web-atlas/src/gql/graphql.ts")).toBe(true);
    expect(ignored("packages/web/src/gql/gql.ts")).toBe(true);
    expect(ignored("packages/web/src/gql/fragment-masking.ts")).toBe(true);
  });

  it("leaves hand-written source untouched", () => {
    expect(ignored("src/lib/service.ts")).toBe(false);
    expect(ignored("api/service.go")).toBe(false);
    expect(ignored("proto/helpers.py")).toBe(false);
    expect(ignored("lib/model.dart")).toBe(false);
  });
});
